#include "chart.h"

// GENERATED FILE -- do not hand-edit. Regenerate with tools/make_chart.py.
//
// "Never Gonna Give You Up" is charted directly from MIDI note-on events and
// tempo messages. Two lanes: drum membranes (kick, snare, toms) on MIDDLE,
// metal (hats, cymbals) on TOP. A MIDI sixteenth collects simultaneous layers,
// then spacing rules retain a playable rhythm. The same MIDI source generates
// music.c, so the notes and the music share one tempo map and cannot drift.
//
// 89 notes, 1.56/s; 56.9s.

static const ChartNote s_demo_notes[] = {
  {   2254, RB_LANE_TOP , RB_NOTE_BIG    },
  {   2508, RB_LANE_MID , RB_NOTE_BIG    },
  {   2763, RB_LANE_TOP , RB_NOTE_BIG    },
  {   3271, RB_LANE_MID , RB_NOTE_BIG    },
  {   4542, RB_LANE_MID , RB_NOTE_BIG    },
  {   5051, RB_LANE_TOP , RB_NOTE_BIG    },
  {   5305, RB_LANE_MID , RB_NOTE_BIG    },
  {   5813, RB_LANE_MID , RB_NOTE_BIG    },
  {   6068, RB_LANE_TOP , RB_NOTE_BIG    },
  {   6576, RB_LANE_TOP , RB_NOTE_BIG    },
  {   8610, RB_LANE_MID , RB_NOTE_BIG    },
  {   9118, RB_LANE_TOP , RB_NOTE_BIG    },
  {   9373, RB_LANE_MID , RB_NOTE_BIG    },
  {   9627, RB_LANE_TOP , RB_NOTE_BIG    },
  {  10390, RB_LANE_TOP , RB_NOTE_BIG    },
  {  10644, RB_LANE_MID , RB_NOTE_BIG    },
  {  10898, RB_LANE_TOP , RB_NOTE_BIG    },
  {  11407, RB_LANE_MID , RB_NOTE_BIG    },
  {  12678, RB_LANE_MID , RB_NOTE_BIG    },
  {  13186, RB_LANE_TOP , RB_NOTE_BIG    },
  {  13695, RB_LANE_MID , RB_NOTE_BIG    },
  {  14203, RB_LANE_TOP , RB_NOTE_BIG    },
  {  14711, RB_LANE_TOP , RB_NOTE_BIG    },
  {  15220, RB_LANE_TOP , RB_NOTE_BIG    },
  {  16237, RB_LANE_TOP , RB_NOTE_BIG    },
  {  17762, RB_LANE_TOP , RB_NOTE_BIG    },
  {  18271, RB_LANE_TOP , RB_NOTE_BIG    },
  {  18779, RB_LANE_TOP , RB_NOTE_BIG    },
  {  19288, RB_LANE_TOP , RB_NOTE_BIG    },
  {  19796, RB_LANE_MID , RB_NOTE_BIG    },
  {  21321, RB_LANE_MID , RB_NOTE_BIG    },
  {  21830, RB_LANE_TOP , RB_NOTE_BIG    },
  {  22084, RB_LANE_MID , RB_NOTE_BIG    },
  {  22847, RB_LANE_TOP , RB_NOTE_BIG    },
  {  23864, RB_LANE_MID , RB_NOTE_BIG    },
  {  24372, RB_LANE_TOP , RB_NOTE_BIG    },
  {  24881, RB_LANE_TOP , RB_NOTE_BIG    },
  {  25898, RB_LANE_MID , RB_NOTE_BIG    },
  {  26406, RB_LANE_TOP , RB_NOTE_BIG    },
  {  26915, RB_LANE_TOP , RB_NOTE_BIG    },
  {  27550, RB_LANE_TOP , RB_NOTE_BIG    },
  {  27931, RB_LANE_MID , RB_NOTE_BIG    },
  {  28440, RB_LANE_TOP , RB_NOTE_BIG    },
  {  28948, RB_LANE_TOP , RB_NOTE_BIG    },
  {  29584, RB_LANE_MID , RB_NOTE_BIG    },
  {  29965, RB_LANE_MID , RB_NOTE_BIG    },
  {  30220, RB_LANE_TOP , RB_NOTE_BIG    },
  {  30982, RB_LANE_TOP , RB_NOTE_BIG    },
  {  31999, RB_LANE_MID , RB_NOTE_BIG    },
  {  32508, RB_LANE_TOP , RB_NOTE_BIG    },
  {  33016, RB_LANE_TOP , RB_NOTE_BIG    },
  {  34033, RB_LANE_MID , RB_NOTE_BIG    },
  {  34541, RB_LANE_TOP , RB_NOTE_BIG    },
  {  35050, RB_LANE_TOP , RB_NOTE_BIG    },
  {  35685, RB_LANE_TOP , RB_NOTE_BIG    },
  {  36067, RB_LANE_MID , RB_NOTE_BIG    },
  {  36575, RB_LANE_TOP , RB_NOTE_BIG    },
  {  37084, RB_LANE_TOP , RB_NOTE_BIG    },
  {  37846, RB_LANE_MID , RB_NOTE_BIG    },
  {  38355, RB_LANE_MID , RB_NOTE_BIG    },
  {  38609, RB_LANE_TOP , RB_NOTE_BIG    },
  {  39118, RB_LANE_TOP , RB_NOTE_BIG    },
  {  41151, RB_LANE_MID , RB_NOTE_BIG    },
  {  41660, RB_LANE_TOP , RB_NOTE_BIG    },
  {  42168, RB_LANE_TOP , RB_NOTE_BIG    },
  {  42931, RB_LANE_MID , RB_NOTE_BIG    },
  {  45219, RB_LANE_MID , RB_NOTE_BIG    },
  {  45728, RB_LANE_TOP , RB_NOTE_BIG    },
  {  45982, RB_LANE_MID , RB_NOTE_BIG    },
  {  46490, RB_LANE_MID , RB_NOTE_BIG    },
  {  46744, RB_LANE_TOP , RB_NOTE_BIG    },
  {  47253, RB_LANE_TOP , RB_NOTE_BIG    },
  {  48270, RB_LANE_TOP , RB_NOTE_BIG    },
  {  49287, RB_LANE_MID , RB_NOTE_BIG    },
  {  49795, RB_LANE_TOP , RB_NOTE_BIG    },
  {  50049, RB_LANE_MID , RB_NOTE_BIG    },
  {  50304, RB_LANE_TOP , RB_NOTE_BIG    },
  {  51066, RB_LANE_TOP , RB_NOTE_BIG    },
  {  51321, RB_LANE_MID , RB_NOTE_BIG    },
  {  51575, RB_LANE_TOP , RB_NOTE_BIG    },
  {  52083, RB_LANE_MID , RB_NOTE_BIG    },
  {  53354, RB_LANE_MID , RB_NOTE_BIG    },
  {  53863, RB_LANE_TOP , RB_NOTE_BIG    },
  {  54371, RB_LANE_MID , RB_NOTE_BIG    },
  {  54880, RB_LANE_TOP , RB_NOTE_BIG    },
  {  55388, RB_LANE_TOP , RB_NOTE_BIG    },
  {  55897, RB_LANE_TOP , RB_NOTE_BIG    },
  {  56914, RB_LANE_TOP , RB_NOTE_BIG    },
  {  58439, RB_LANE_TOP , RB_NOTE_BIG    },
};

static const Chart s_demo_chart = {
  .title = "Never Gonna Give You Up",
  .notes = s_demo_notes,
  .note_count = (uint16_t)(sizeof(s_demo_notes) / sizeof(s_demo_notes[0])),
  .bpm = 118,
  .lead_in_ms = 2000,
  .end_ms = 61448,
};

const Chart *chart_get_builtin(void) { return &s_demo_chart; }

bool chart_load_from_resource(uint32_t resource_id, Chart *out_chart) {
  (void)resource_id;
  (void)out_chart;
  return false;
}
